### ISSUE TITLE
More cloacked CNAME trackers🤯

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/cname-trackers#6]
Hi,

you can find more cloacked CNAME trackers in the [attached file](https://github.com/AdguardTeam/cname-trackers/files/6175229/cname.txt). I hope it will be useful🤗

Please, take a look! This tracker list will be also included to AdGuard DNS filter?🤔

Thank you.
Cheers✌🏻

**Comment by TPS** [comment]
@ammnt Wow, how did you generate all these?

**Comment by ameshkov** [comment]
> This tracker list will be also included to AdGuard DNS filter?🤔

Nope, AdGuard DNS is able to scan CNAME records, it does not need it.

Also, this repo is auto-generated, we only need to know new "original" trackers: https://github.com/AdguardTeam/cname-trackers/blob/master/combined_original_trackers.txt

Disguised trackers are not that needed since they'll be included automatically (as long as they're actively used).
