### ISSUE TITLE
Request for consent to use products of this list in a derivative work

### ISSUE THREAD

**Issue by StevenBlack** [AdguardTeam/cname-trackers#7]
👋  Hello Andrey @ameshkov and Slava @slavaleleka. 

I am considering adding `cname-trackers` to my amalgamated hosts file at https://github.com/StevenBlack/hosts.

[Discussion here](https://github.com/StevenBlack/hosts/issues/1563).

This would go in the base list, which is included in all the optional variants we produce — for porn, social media, gambling, fake news, and combinations of those.

I see your license permits this derivative use, but I always ask first.

Good?

Thank you!

**Comment by TPS** [comment]
Local discussion @ https://github.com/AdguardTeam/cname-trackers/issues/3

**Comment by ameshkov** [comment]
Hi @StevenBlack, no problem, feel free to use it.

I'd just like to note, that the "combined" list might be pretty aggressive since some of these domains are used not only for tracking and ads but also for other purposes.

Please check the original trackers list:
https://github.com/AdguardTeam/cname-trackers/blob/master/combined_original_trackers.txt

If you're blocking all of these domains in your list, it'd be safe to include all of them.
If you'd like to avoid blocking some of them, you can pick the ones you need from https://github.com/AdguardTeam/cname-trackers/tree/master/trackers

**Comment by StevenBlack** [comment]
Thank you Andrey @ameshkov!
